// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwBs9HqFeieF7fp4DQVUcQGaiKazbhCe0',
    appId: '1:1064548163853:web:e1414f6b40eaad42879044',
    messagingSenderId: '1064548163853',
    projectId: 'teslogin-caab5',
    authDomain: 'teslogin-caab5.firebaseapp.com',
    databaseURL: 'https://teslogin-caab5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'teslogin-caab5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC63Fe2d1Zjfn5jk1WLROnzg_rPhRI_9rg',
    appId: '1:1064548163853:android:efcf4bbfedc47f2a879044',
    messagingSenderId: '1064548163853',
    projectId: 'teslogin-caab5',
    databaseURL: 'https://teslogin-caab5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'teslogin-caab5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJV_O8mP8gF15s-a_8iyKvkg7VQQbwp44',
    appId: '1:1064548163853:ios:712db450d3db073a879044',
    messagingSenderId: '1064548163853',
    projectId: 'teslogin-caab5',
    databaseURL: 'https://teslogin-caab5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'teslogin-caab5.firebasestorage.app',
    androidClientId: '1064548163853-m71q5ikbscavpughuo4n748p5ifej9ig.apps.googleusercontent.com',
    iosClientId: '1064548163853-dpqc051a0dod9gi9hkup88mjdn04srlr.apps.googleusercontent.com',
    iosBundleId: 'com.example.teslogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJV_O8mP8gF15s-a_8iyKvkg7VQQbwp44',
    appId: '1:1064548163853:ios:712db450d3db073a879044',
    messagingSenderId: '1064548163853',
    projectId: 'teslogin-caab5',
    databaseURL: 'https://teslogin-caab5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'teslogin-caab5.firebasestorage.app',
    androidClientId: '1064548163853-m71q5ikbscavpughuo4n748p5ifej9ig.apps.googleusercontent.com',
    iosClientId: '1064548163853-dpqc051a0dod9gi9hkup88mjdn04srlr.apps.googleusercontent.com',
    iosBundleId: 'com.example.teslogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwBs9HqFeieF7fp4DQVUcQGaiKazbhCe0',
    appId: '1:1064548163853:web:e1414f6b40eaad42879044',
    messagingSenderId: '1064548163853',
    projectId: 'teslogin-caab5',
    authDomain: 'teslogin-caab5.firebaseapp.com',
    databaseURL: 'https://teslogin-caab5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'teslogin-caab5.firebasestorage.app',
  );

}